# Generated by Django 5.2.3 on 2026-04-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf_name',
            new_name='doc_name',
        ),
    ]
